run:
  go: '1.22'

issues:
  exclude-dirs:
    - vendor
    - pkg/discovery/kubernetes/client

linters:
  disable-all: true
  enable:
    - unused
    - ineffassign   # Detects when assignments to existing variables are not used
    - staticcheck   # Staticcheck is a go vet on steroids, applying a ton of static analysis checks
    - unused        # Checks Go code for unused constants, variables, functions and types
    - asciicheck
    - errorlint
    - importas
    - tparallel
    - bodyclose

linters-settings:
  govet:
    shadow: true
    check-unreachable: true
    check-rangeloops: true
    check-copylocks: true
